name: 2020 CI

on:
  push:
    paths: 
      - 2020/**


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use dmd
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: dmd-latest  
      - run: dmd -unittest -run *.d
        working-directory: "2020"

